apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: billing-api-secrets
  namespace: payments
  labels:
    app.kubernetes.io/name: billing-api
    app.kubernetes.io/instance: billing-api-prod
    team: payments
    env: prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: billing-api-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/billing-api/env
